
import Foundation

struct DataSource {
	static let weatherIDsEn: [Int: String] = [
        200: "thunderstorm with light rain",
        201: "thunderstorm with rain",
        202: "small thunderstorm",
        210: "thunderstorm with heavy rain",
        211: "thunderstorm",
        212: "heavy thunderstorm",
        221: "the strongest thunderstorm",
        230: "thunderstorm with light rain",
        231: "thunderstorm with rain",
        232: "thunderstorm with heavy rain",
        300: "light drizzle",
        301: "light rain",
        302: "heavy drizzle",
        310: "intense drizzling rain",
        311: "drizzling rain",
        312: "heavy drizzle",
        313: "rain and drizzle",
        314: "heavy rain and drizzle",
        321: "downpour",
        500: "small rain",
        501: "moderate rain",
        502: "heavy intense rain",
        503: "very heavy rain",
        504: "extreme rain",
        511: "freezing rain",
        520: "short downpour",
        521: "pouring rain",
        522: "heavy downpour",
        531: "heavy downpour",
        600: "light snow",
        601: "snow",
        602: "heavy snow",
        611: "wet snow",
        612: "rain with snow",
        615: "light rain and snow",
        616: "rain and snow",
        620: "light snowfall",
        621: "snowfall",
        622: "heavy snowfall",
        701: "overcast",
        711: "smoke",
        721: "haze",
        731: "sand, dust whirlwinds",
        741: "fog",
        751: "sand",
        761: "dust",
        762: "volcanic ash",
        771: "squall",
        781: "tornado",
        800: "clear sky",
        801: "some clouds",
        802: "scattered clouds",
        803: "torn clouds",
        804: "mainly cloudy"
	]
    
    static let weatherIDsRu: [Int: String] = [
        200: "гроза с небольшим дождем",
        201: "гроза с дождем",
        202: "гроза с сильным дождем",
        210: "небольшая гроза",
        211: "гроза",
        212: "сильная гроза",
        221: "сильнейшая гроза",
        230: "гроза с небольшим дождем",
        231: "гроза с дождем",
        232: "гроза с сильным дождем",
        300: "легкий моросящий дождь",
        301: "мелкий дождь",
        302: "сильный моросящий дождь",
        310: "интенсивный моросящий дождь",
        311: "моросящий дождь",
        312: "сильный моросящий дождь",
        313: "ливень и изморось",
        314: "сильный ливень и изморось",
        321: "ливневый дождь",
        500: "небольшой дождь",
        501: "умеренный дождь",
        502: "сильный интенсивный дождь",
        503: "очень сильный дождь",
        504: "экстремальный дождь",
        511: "ледянной дождь",
        520: "непродолжительный ливень",
        521: "проливной дождь",
        522: "продолжительный ливень",
        531: "сильнейший ливень",
        600: "небольшой снег",
        601: "снег",
        602: "сильный снег",
        611: "мокрый снег",
        612: "дождь со снегом",
        615: "небольшой дождь и снег",
        616: "дождь и снег",
        620: "небольшой снегопад",
        621: "снегопад",
        622: "сильный снегопад",
        701: "пасмурность",
        711: "дым",
        721: "дымка",
        731: "песок, пылевые вихри",
        741: "туман",
        751: "песок",
        761: "пыль",
        762: "вулканический пепел",
        771: "шквал",
        781: "торнадо",
        800: "чистое небо",
        801: "немного облаков",
        802: "рассеянные облака",
        803: "рванные облака",
        804: "пасмурно"
    ]
}
