
import Foundation

struct DataSource {
	static let weatherIDsEn: [Int: String] = [
        200: "thunderstorm with light rain",
        201: "thunderstorm with rain",
        202: "small thunderstorm",
        210: "thunderstorm with heavy rain",
        211: "thunderstorm",
        212: "heavy thunderstorm",
        221: "the strongest thunderstorm",
        230: "thunderstorm with light rain",
        231: "thunderstorm with rain",
        232: "thunderstorm with heavy rain",
        300: "light drizzle",
        301: "light rain",
        302: "heavy drizzle",
        310: "intense drizzling rain",
        311: "drizzling rain",
        312: "heavy drizzle",
        313: "rain and drizzle",
        314: "heavy rain and drizzle",
        321: "downpour",
        500: "small rain",
        501: "moderate rain",
        502: "heavy intense rain",
        503: "very heavy rain",
        504: "extreme rain",
        511: "freezing rain",
        520: "short downpour",
        521: "pouring rain",
        522: "heavy downpour",
        531: "heavy downpour",
        600: "light snow",
        601: "snow",
        602: "heavy snow",
        611: "wet snow",
        612: "rain with snow",
        615: "light rain and snow",
        616: "rain and snow",
        620: "light snowfall",
        621: "snowfall",
        622: "heavy snowfall",
        701: "overcast",
        711: "smoke",
        721: "haze",
        731: "sand, dust whirlwinds",
        741: "fog",
        751: "sand",
        761: "dust",
        762: "volcanic ash",
        771: "squall",
        781: "tornado",
        800: "clear sky",
        801: "some clouds",
        802: "scattered clouds",
        803: "torn clouds",
        804: "mainly cloudy"
	]
    
    static let weatherIDsRu: [Int: String] = [
        200: "thunderstorm with light rain",
        201: "thunderstorm with rain",
        202: "small thunderstorm",
        210: "thunderstorm with heavy rain",
        211: "thunderstorm",
        212: "heavy thunderstorm",
        221: "the strongest thunderstorm",
        230: "thunderstorm with light rain",
        231: "thunderstorm with rain",
        232: "thunderstorm with heavy rain",
        300: "light drizzle",
        301: "light rain",
        302: "heavy drizzle",
        310: "intense drizzling rain",
        311: "drizzling rain",
        312: "heavy drizzle",
        313: "rain and drizzle",
        314: "heavy rain and drizzle",
        321: "downpour",
        500: "small rain",
        501: "moderate rain",
        502: "heavy intense rain",
        503: "very heavy rain",
        504: "extreme rain",
        511: "freezing rain",
        520: "short downpour",
        521: "pouring rain",
        522: "heavy downpour",
        531: "heavy downpour",
        600: "light snow",
        601: "snow",
        602: "heavy snow",
        611: "wet snow",
        612: "rain with snow",
        615: "light rain and snow",
        616: "rain and snow",
        620: "light snowfall",
        621: "snowfall",
        622: "heavy snowfall",
        701: "overcast",
        711: "smoke",
        721: "haze",
        731: "sand, dust whirlwinds",
        741: "fog",
        751: "sand",
        761: "dust",
        762: "volcanic ash",
        771: "squall",
        781: "tornado",
        800: "clear sky",
        801: "some clouds",
        802: "scattered clouds",
        803: "torn clouds",
        804: "Залупа"
    ]
}
